import Head from 'next/head';
import { Inter } from 'next/font/google';
import EventList from '@/components/events/event-list';
// import { getFeaturedEvents } from 'dummy-data';
import { getFeaturedEvents } from 'helpers/api-util';

const inter = Inter({ subsets: ['latin'] });

export default function Home(props) {
    // const featuredEvents = getFeaturedEvents();

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${inter.className}`}>
                <EventList items={props.featuredEvents} />
            </main>
        </>
    );
}

export async function getStaticProps() {
    const featuredEvents = await getFeaturedEvents();

    return { props: { featuredEvents }, revalidate: 1800 };
}
