import { Inter } from 'next/font/google';
import Head from 'next/head';
import { useRef, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    const [feedbackItems, setFeedbackItems] = useState([]);
    const emailInputRef = useRef();
    const feedbackInputRef = useRef();

    const submitFormHandler = (e) => {
        e.preventDefault();
        const enteredEmail = emailInputRef.current.value;
        const enteredFeedback = feedbackInputRef.current.value;
        const reqBody = { email: enteredEmail, text: enteredFeedback };

        fetch('/api/feedback', {
            method: 'POST',
            body: JSON.stringify(reqBody),
            headers: {
                'Content-Type': 'application/json',
            },
        })
            .then((response) => response.json())
            .then((data) => console.log(data));
    };

    const loadFeedbackHandler = () => {
        fetch('/api/feedback')
            .then((response) => response.json())
            .then((data) => {
                setFeedbackItems(data.feedback);
            });
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={inter.className}>
                <h1>This is Home page</h1>
                <form onSubmit={submitFormHandler}>
                    <div>
                        <label htmlFor="email">Your Email Address</label>
                        <input type="email" id="email" ref={emailInputRef} />
                    </div>
                    <div>
                        <label htmlFor="feedback">Your Feedback</label>
                        <textarea
                            id="feedback"
                            rows="5"
                            ref={feedbackInputRef}
                        ></textarea>
                    </div>
                    <button>Send Feedback</button>
                </form>
                <hr />
                <button onClick={loadFeedbackHandler}>Load Feedback</button>
                <ul>
                    {feedbackItems && feedbackItems.map((item) => (
                        <li key={item.id}>{item.text}</li>
                    ))}
                </ul>
            </main>
        </>
    );
}
